name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Build
        run: go build -v ./...

      - name: Run unit tests
        run: make test.unit

      - name: Run integration tests
        run: make test.integration

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
